### ISSUE TITLE
I take back my last comment, if a SW representation of NDCR was used then less register read/writes could be done

### ISSUE THREAD

**Issue by oferhz** [miquelraynal/linux#16]
https://github.com/miquelraynal/linux/blob/ed97672cb248ece96dd621336ead3030390f2eb8/drivers/mtd/nand/marvell_nand.c#L1269

**Comment by miquelraynal** [comment]
Hello Ofer,
I don't really understand what you mean here.
I think keeping a static variable with the NDCR representation is a terrible idea and could cause obscure errors. The overhead of a readl_relaxed is negligible compared to a full page read/write and most of the time (if not all the time actually) the read will be mandatory when enabling/disabling the ECC engine  no matter if we stored the information if the engine is on/off because other bits in the register could have flipped.

**Comment by oferhz** [comment]
Hi,
Well I thought of setting representation rather thata full register value, but if from your benchmarking/trace you see that it is negligible, then forget about it
