### ISSUE TITLE
shouldnt this routine return some error code for the invoker to know that it failed?

### ISSUE THREAD

**Issue by oferhz** [miquelraynal/linux#2]
https://github.com/miquelraynal/linux/blob/0f8c5616d18b91ffa09cad98188530520bca6729/drivers/mtd/nand/marvell_nand.c#L393

**Comment by miquelraynal** [comment]
I changed the type of this function to return an int, but I don't see a use case for it because the user will have been notified and later operations (read/writes) would fail anyway, there is nothing we can do in that case (which is, BTW, quite unlikely).

Nonetheless, I added some logic in the functions calling ->nfc_prepare_cmd() to raise the error whenever they are returning something (most of them return void and are core's hooks).

Thanks for the comment,
Miquèl
